{% set version = "0.4.1" %}

package:
  name: pywebhdfs
  version: {{ version }}

source:
  fn: pywebhdfs-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/pywebhdfs/pywebhdfs-{{ version }}.tar.gz
  md5: 4e7866940d77bf880cce5eba2ef75ece

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pbr

  run:
    - python >={{ python_min }}
    - requests
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - pywebhdfs

about:
  home: https://github.com/pywebhdfs/pywebhdfs/
  license: Apache-2.0
  summary: Python wrapper for the hadoop WebHDFS Rest API
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frol
